<h2>Login example</h2>

<p>Hello! You should be able to see this page after you log in.</p>

<p>Your username is <?= $this->username ?>, your real name is <?= $this->name ?>
 and you used <?= $this->email ?> as your E-mail during registration.</p>

<p>Go to <a href="<?= $this->url(array('action'=>'another','controller'=>'index')); ?>">another page</a></p>

<p><a href="<?= $this->url(array('action'=>'logout','controller'=>'login')); ?>">logout</a>